export interface Estacao {
    id: string,
    nome: string,
    uid: string,
    cep: string,
    numero: number,
    bairro: string,
    cidade: string,
    rua: string,
    latitude: string,
    longitude: string,
    atualizadoEm: string,
    criadoEm: string,
    parametros: string[], 
}
